version: 2
jobs:
  build:
    docker:
      # circleci/ruby:2.4-node-browsers + awscli
      - image: kenmickles/fftf-static-site-builder:0.0.2

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: |
            npm install

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Build
          command: |
            npm run generate

      - deploy:
          name: Deploy to Web Server
          command: |
            ssh-keyscan static1.fightforthefuture.org >> ~/.ssh/known_hosts
            npm run deploy

      - run:
          name: Purge CloudFlare cache
          command: |
            curl -X DELETE "https://cloudflare.fftf.xyz/zones/${CLOUDFLARE_ZONE_ID}/cache" \
              -H "X-Auth-Key: ${CLOUDFLARE_ZONE_KEY}"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
